#!/usr/bin/env python3
import json
import requests

POSTS_URL = "http://localhost:4000/posts"


def create_post(post):
    headers = {
        "Content-Type": "application/json"
    }
    res = requests.post(POSTS_URL, data=json.dumps(post), headers=headers)

    if res.status_code == 201:
        print("created post: {}".format(post))
    else:
        print("error creating post")


ps = [
    {"title": "Hello World"},
    {"title": "Second Post"},
    {"title": "Third Post"},
]

for p in ps:
    create_post(p)
