apiVersion: apps/v1
kind: Deployment
metadata:
    name: posts-depl
spec:
    # number of pods to run
    replicas: 1
    selector:
        matchLabels:
            app: posts
    template:
        metadata:
            labels:
                app: posts
        spec:
            containers:
                - name: posts
                  image: microservice_course/posts
